### ISSUE TITLE
omnihouse gt

### ISSUE THREAD

**Issue by imuncle** [matsuren/omnimvs_pytorch#10]
Hi, I have a trouble with omnihouse groundtruth. Sorry for ask you, but I cant contact with the author of dataset.

I download the omnihouse dataset from [omnistereo](http://cvlab.hanyang.ac.kr/project/omnistereo/), but the groudtruth I got is in `tiff` format, as follows:

![image](https://user-images.githubusercontent.com/35989223/145674568-e027c4bb-dc3c-4941-a3fc-d6a539c741a1.png)

The value is arroud in 0-255, not 0-65500, as described in the dataset.

And I have tried to use your code:

```python
def load_invdepth(filename, min_depth=55):
    '''
    min_depth in [cm]
    '''
    invd_value = cv2.imread(filename, cv2.IMREAD_ANYDEPTH)
    invdepth = (invd_value / 100.0) / (min_depth * 655) + np.finfo(np.float32).eps
    invdepth *= 100  # unit conversion from cm to m
    return invdepth
```

but I got wrong result.

Is there something I was wrong? If I download wrong groudtruth, could you tell me where to find the right one?

Thanks a lot!

**Comment by imuncle** [comment]
I think the groundtruth can't be used now, it's broken. I also tried the method in #5 ,but I also can't train to abtain a good result. However the dataset in [http://vclab.kaist.ac.kr/cvpr2021p1/](http://vclab.kaist.ac.kr/cvpr2021p1/) is able to use, so the problem is not in my code.

Do you still have the ground truth you downloaded in `png` format? Could you share it to me?

**Comment by wangyushen** [comment]
> I think the groundtruth can't be used now, it's broken. I also tried the method in #5 ,but I also can't train to abtain a good result. However the dataset in http://vclab.kaist.ac.kr/cvpr2021p1/ is able to use, so the problem is not in my code.
> 
> Do you still have the ground truth you downloaded in `png` format? Could you share it to me?

I have the same problem as you. In the omnimvs (CVPR) code, there is a code to extract the TIFF format Ground-Truth, but the  disparity map looks wrong after using. In the second layer of the current dataset, you can see the GT as the example.

**Comment by wangyushen** [comment]
> I think the groundtruth can't be used now, it's broken. I also tried the method in #5 ,but I also can't train to abtain a good result. However the dataset in http://vclab.kaist.ac.kr/cvpr2021p1/ is able to use, so the problem is not in my code.
> 
> Do you still have the ground truth you downloaded in `png` format? Could you share it to me?

I have the same problem as you. In the omnimvs (CVPR)  has code to extract the TIFF format Ground-Truth, but the disparity map looks wrong after using. In the second layer of the current dataset, you can see the GT as the example.

**Comment by imuncle** [comment]
> > I think the groundtruth can't be used now, it's broken. I also tried the method in #5 ,but I also can't train to abtain a good result. However the dataset in http://vclab.kaist.ac.kr/cvpr2021p1/ is able to use, so the problem is not in my code.
> > Do you still have the ground truth you downloaded in `png` format? Could you share it to me?
> 
> I have the same problem as you. In the omnimvs (CVPR) has code to extract the TIFF format Ground-Truth, but the disparity map looks wrong after using. In the second layer of the current dataset, you can see the GT as the example.

Sorry, what do you mean by 'the second layer' ?

**Comment by wangyushen** [comment]
> > > I think the groundtruth can't be used now, it's broken. I also tried the method in #5 ,but I also can't train to abtain a good result. However the dataset in http://vclab.kaist.ac.kr/cvpr2021p1/ is able to use, so the problem is not in my code.
> > > Do you still have the ground truth you downloaded in `png` format? Could you share it to me?
> > 
> > 
> > I have the same problem as you. In the omnimvs (CVPR) has code to extract the TIFF format Ground-Truth, but the disparity map looks wrong after using. In the second layer of the current dataset, you can see the GT as the example.
> 
> Sorry, what do you mean by 'the second layer' ?

A TIFF format file contains multiple pictures, and the TIFF format file in this dataset contains two pictures, the first is a 3-channel picture and the second is a single channel picture. The second image is very similar to the disparity map, but it is treated as a depth map in OmniMVS (CVPR). The processed image is not like the correct disparity map. 
![QQ截图20211214210603](https://user-images.githubusercontent.com/45096484/146004154-2fb233df-fec3-4970-a354-ec993bdce6c8.png)

**Comment by imuncle** [comment]
@wangyushen Great! You have solved my problem. Thanks bro!

**Comment by wangyushen** [comment]
> @wangyushen Great! You have solved my problem. Thanks bro!

How did you solve this problem? Could you please share the code of data loading?

**Comment by imuncle** [comment]
The second layer is exactly the invdepth, and it does not need any more transformation.

```python
from PIL import Image
import numpy as np
gt = Image.open('00001.tiff')
gt.seek(1)    # get the second layer
gt = np.array(gt) # this is the invdepth
# by using gt = 1/gt you can get the depth in meters
```

What's more, the distance between camera and the center of rig is 0.6m, not 0.2m. So the `config.yaml` is true, and the `poses.txt` is wrong. 

I verify it by wraping the groudtruth from `Equidistant projection` to the `fisheye projection`. When I suppose the distance is 0.6m, I got the following result:

![image](https://user-images.githubusercontent.com/35989223/146181008-b192675d-e2f3-4252-a384-f7e4a7ac944e.png)

As you can see, the depth overlaps perfectly with the image

**Comment by matsuren** [comment]
Sorry for late reply, and thank you for great discussion!
It's better to mention in #8 about wrong extrinsic parameters. I should've been more skeptical about the extrinsic parameters.
