### ISSUE TITLE
Can provide a pre-trained model

### ISSUE THREAD

**Issue by huhumeng2** [matsuren/omnimvs_pytorch#2]
hi, I want to test this network but i found download this dataset is to slow, can you give a pre-trained model so I could test on my data, thanks a lot :-)

**Comment by matsuren** [comment]
Hi, 
Thank you for your interest. I have a plan to upload the pre-trained model once I organize some source code to visualize the estimated depth. Please wait for a while.
Thanks,

**Comment by matsuren** [comment]
Hi,
I think I can provide the pre-trained model. Please wait for a while. 
Thanks,

**Comment by matsuren** [comment]
Hi, 
I just uploaded a pre-trained model (ndisp=48) [here](https://1drv.ms/u/s!Ao6oo2sMuht4tyd5tU1OS0hNjzNb?e=rez8E0).
Let me know if you have any problems with it.
Thanks,
