### ISSUE TITLE
one question about the predict value

### ISSUE THREAD

**Issue by Lsm67** [matsuren/omnimvs_pytorch#5]
Thank you very much for sharing.
I encountered a problem that the resulting predicted disparity maps were completely black, while training the data without pre-trained weight file. By printing the data, I found that all the data in tensor "gt_invd_idx"  from training dataset were 0, and the data in tensor  "pred" which is the output of network model was 0~1 . Can I ask what is wrong? Thank you!

**Comment by matsuren** [comment]
Thank you for your comment.

Could you check if `gt_idepth` has the collect value? Because `gt_invd_idx` is calculated by the following code
`gt_invd_idx = converter.invdepth_to_index(gt_idepth)`

Thank you,

**Comment by matsuren** [comment]
Also, please consider using the official implementation available [here](https://github.com/hyu-cvlab/omnimvs-pytorch).

**Comment by ouhuajing** [comment]
> Thank you very much for sharing.
> I encountered a problem that the resulting predicted disparity maps were completely black, while training the data without pre-trained weight file. By printing the data, I found that all the data in tensor "gt_invd_idx" from training dataset were 0, and the data in tensor "pred" which is the output of network model was 0~1 . Can I ask what is wrong? Thank you!

I encountered the same problem and the gt_idepth is so small less than 0.01. Do you have a solution ?

**Comment by matsuren** [comment]
Could you visualize `gt_idepth` using something like `plt.imshow` to make sure that you load dataset correctly? If all values are small, I guess you failed to load dataset.

**Comment by Lsm67** [comment]
Thanks a million to both of you for sharing. 
Referring to your suggestions, I have finished a training model for these days. After modifying the function load_invdepth(),invdepth_to_index(),index_to_invdepth, I trained a model on sunny dataset for 200 epochs, 900 training pictures, although the evaluation "a1" is 54.8 . 
The final disparity map is not as good as the one which the author shows. Maybe because the training data set is not enough.
thank you!!!

**Comment by ouhuajing** [comment]
> Thanks a million to both of you for sharing.
> Referring to your suggestions, I have finished a training model for these days. After modifying the function load_invdepth(),invdepth_to_index(),index_to_invdepth, I trained a model on sunny dataset for 200 epochs, 900 training pictures, although the evaluation "a1" is 54.8 .
> The final disparity map is not as good as the one which the author shows. Maybe because the training data set is not enough.
> thank you!!!

Thank you very much. Could you please give the modified function code?

**Comment by matsuren** [comment]
I think it's ok to close now.
