### ISSUE TITLE
one question about the format of depth image

### ISSUE THREAD

**Issue by takuya-ikeda-tri** [matsuren/omnimvs_pytorch#7]
I have a one question about depth image format.
I cannot find `depth_train_640/` in omnithings directory which is downloaded from [here](http://cvlab.hanyang.ac.kr/project/omnistereo/). But, I can see the gt depth images in [Omnidirectional Stereo Dataset](https://bit.ly/33hqvcl). This depth format looks `tiff`.
Your `depth_train_640` meant to be the above depth images? In this case, should I convert from `tiff` to `png` by myself?
BTW, thank you for all of your awesome work!

**Comment by matsuren** [comment]
Hi,

I think they changed ground truth format for depth image. The last time I downloaded, the depth image format was png. Please change filename in `omnithings_train.txt` and `omnithings_train.txt`. Also, I guess you need to change the loading function [here](https://github.com/matsuren/omnimvs_pytorch/blob/c24d182372503235075cd0a3e1d8011a656e8f2e/dataloader/omnistereo_dataset.py#L56). 

Thanks,

**Comment by takuya-ikeda-tri** [comment]
I understand. Thank you for your feedback!

**Comment by EchoTHChen** [comment]
Sorry to bother you! @takuya-ikeda-tri How did you turn depthmap from the .tiff to .png format? I'm not familiar to .tiff

**Comment by EchoTHChen** [comment]
It seems that the .tiff has three channels. How can I turn it to one-channel depth?
