### ISSUE TITLE
wrong extrinsics

### ISSUE THREAD

**Issue by Siidej** [matsuren/omnimvs_pytorch#8]
Hi, 

Thank you for sharing the code, I think they've made a mistake in their datasets. For cameras' extrinsic, the config.yaml is more corresponding than the poses.txt.
For example, pose_cam2 should be : [0.000000, 1.570796326794897, 0.000000, 60.00000, 0.000000, 0.000000] (should in centimetres btw)
Rather than : [0.000000 1.570796326794897 0.000000 20.000000 0.000000 -20.000000]

Cheers

**Comment by matsuren** [comment]
Thank you for your information. But, I don't know which datasets you're talking about. At least, omnihouse and omnithings datasets seems to be correct for me.

Thanks,

**Comment by Siidej** [comment]
Hello,
I've tested omihouse, it corresponds to its yaml file. I also tested omnithings, and none of its two files works. I think maybe there are some problems after their updating of datasets.
I'm now working with habitat-sim/habitat-lab, and I'd like to thank you for your implementation of the double sphere model !

**Comment by matsuren** [comment]
Sorry for late reply. It's been hectic.
Hmm, the last time i checked omnihouse, the locations of the cameras was something like:
cam0:[0.0, 0.0, 0.0],
cam1:[20.0, 0.0, -20.0],
cam2:[0.0, 0.0, -40.0],
cam3:[-20.0, 0.0, -20.0],

And I visualized the camera pose that seemed to be okay.
You might want to see my notebook to visualize the pose [here](https://github.com/matsuren/omnimvs_pytorch/blob/master/notebook/visualize_datasets.ipynb).

Anyway, thank you for your information. The next I use omnihouse, i will be careful!

> I'm now working with habitat-sim/habitat-lab, and I'd like to thank you for your implementation of the double sphere model!

Glad that you're using double sphere model :smile:

**Comment by matsuren** [comment]
@Siidej 
It seems that you're right about the extrinsic parameters. Check the discussion [here](https://github.com/matsuren/omnimvs_pytorch/issues/10#issuecomment-993522179). The authors of the datasets keep changing so be careful about my source code. The groundtruth depths were provided as png when I downloaded, but it seems that they are provided as tiff.
