### ISSUE TITLE
omnimvs_binocular

### ISSUE THREAD

**Issue by Siidej** [matsuren/omnimvs_pytorch#9]
Hi,

I modified your implementation for applying binocular systems, I hope you don't mind my [borrowing](https://github.com/Siidej/OmniMVS_Binocular).

In haste

**Comment by matsuren** [comment]
Thank you for letting me know! It looks great.
I'm surprised that the data generated by Habitat-Sim doesn't produce good results as in Replica-Dataset. I thought the cubemap hacking is enough for generating fisheye images. How much resolution you used in each cubemap? It might be because of low resolution in cubemap.

**Comment by Siidej** [comment]
> Thank you for letting me know! It looks great.
> I'm surprised that the data generated by Habitat-Sim doesn't produce good results as in Replica-Dataset. I thought the cubemap hacking is enough for generating fisheye images. How much resolution you used in each cubemap? It might be because of low resolution in cubemap.

Thank you for replying, the example here is a 200\*200 downsample of an 800\*800 image. The original 800*800 [image](https://github.com/Siidej/OmniMVS_Binocular/blob/master/images/800.png) (the depth) also has this problem, the RGB images are great.

**Comment by matsuren** [comment]
I see, I guess ground truth of the depth has large error. As you can see from [here](https://github.com/Siidej/OmniMVS_Binocular/blob/master/images/exemple.png), `val/gt` seems to be wrong. It's better to visualize the ground truth as point cloud to see if the ground truth of the depth is correct.

**Comment by Siidej** [comment]
> I see, I guess ground truth of the depth has large error. As you can see from [here](https://github.com/Siidej/OmniMVS_Binocular/blob/master/images/exemple.png), `val/gt` seems to be wrong. It's better to visualize the ground truth as point cloud to see if the ground truth of the depth is correct. 

Yes, all the [ground truths](https://github.com/Siidej/OmniMVS_Binocular/blob/master/images/dataset.png) (even 800\*800) generated by habitat-sim have this problem, and it's interesting to see that this network have learned the error too. I'm not sure if it's the problem of my code of my dataset generator, and I didn't dig into the details of the cubemap hacking, I'll take a look when I have time and open source the dataset generator of this little project then.

**Comment by matsuren** [comment]
I'm not sure if you knew already, but be careful about the depth map for fisheye. My implementation is depth from optical center, so it's better to visualize as pointcloud if the depthmap is correct.
Maybe useful reference.
https://github.com/facebookresearch/habitat-lab/issues/500#issuecomment-713253307
https://github.com/facebookresearch/habitat-lab/pull/517

Thanks,
